version: '3.8'
services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_DB=ZNO
            - POSTGRES_USER=Student
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5432:5432/tcp
        #volumes: 
        #    - pgdata:/var/lib/postgresql/data
    db_client:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=clientpass
        ports:
            - 5050:80
    # flyway:
    #     image: flyway/flyway:9-alpine
    #     depends_on:
    #           - db
    #           - app
    #     environment:
    #        - FLYWAY_USER=Student
    #        - FLYWAY_PASSWORD=qwerty
    #        - FLYWAY_URL=jdbc:postgresql://db:5432/ZNO
    #        - FLYWAY_SCHEMAS=public
    #     volumes:
    #        - ./app/flyway/sql:/flyway/sql 
    #     command: -locations=filesystem:/flyway/sql -baselineVersion=1 -baselineDescription=initial_schema -connectRetries=60 baseline
    app:
        build: ./app
        depends_on:
            - db
        volumes:
            - ./app/data:/app/data
            - ./app/program_output:/app/program_output
            - ./app/flyway/sql:/app/flyway/sql

#volumes:
#    pgdata: