version: '3.8'
services:
    db:
        image: postgres:12-alpine
        container_name: postgresdb
        restart: always
        environment:
            - POSTGRES_DB=ZNO
            - POSTGRES_USER=Student
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5432:5432
        #volumes: 
        #    - pgdata:/var/lib/postgresql/data
    db_client:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=clientpass
        ports:
            - 5050:80
    app:
        build: ./app
        depends_on:
            - db
        volumes:
            - ./app/data:/app/data
            - ./app/program_output:/app/program_output

# volumes:
#     app_data:
#     app_output:
            
         
