version: '3.8'
services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_DB=ZNO
            - POSTGRES_USER=Student
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5432:5432/tcp
        #volumes: 
        #    - pgdata:/var/lib/postgresql/data
    db_client:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=clientpass
        ports:
            - 5050:80
    flyway:
        build: ./app/flyway
        depends_on:
              - db
        # environment:
        #    - FLYWAY_USER=Student
        #    - FLYWAY_PASSWORD=qwerty
        #    - FLYWAY_URL=jdbc:postgresql://postgres:5432/ZNO
        #    - FLYWAY_SCHEMAS=public
        volumes:
           - ./app/flyway/sql:/flyway/sql  
           - ./app/flyway/flyway-config:/flyway/conf/flyway.config 
        # command: -configFiles=/flyway/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    app:
        build: ./app
        depends_on:
            - db
        volumes:
            - ./app/data:/app/data
            - ./app/program_output:/app/program_output
            - ./app/migrations:/app/migrations
