version: '3.8'
services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_DB=ZNO
            - POSTGRES_USER=Student
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5432:5432/tcp
    db_client:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=clientpass
        ports:
            - 5050:80
    flyway:
          image: flyway/flyway:9-alpine
          depends_on:
             - db
          volumes:
             - ./app/flyway/sql:/flyway/sql
             - ./app/flyway/conf:/flyway/conf
          command: -configFiles=/flyway/conf/flyway.conf migrate
    app:
        build: ./app
        depends_on:
            - db
        volumes:
            - ./app/data:/app/data
            - ./app/program_output:/app/program_output
            - ./app/flyway/sql:/app/flyway/sql
