version: '3.8'
#services:
#  app:
#    build: ./app/
#    depends_on:
#      - db
#    volumes:
#      - './app/data:/app/data'
#      - './app/program_output:/app/program_output'
#      - './app/flyway/sql:/app/flyway/sql'
#    networks:
#      - test
#  db:
#    image: postgres:13
#    restart: always
#    environment:
#      - POSTGRES_USER=Student
#      - POSTGRES_PASSWORD=qwerty
#      - POSTGRES_DB=ZNO
#    ports:
#      - '5432:5432'
#    networks:
#      - test
#  flyway:
#    image: flyway/flyway:7
#    depends_on:
#      - db
#    command: -configFiles=/flyway/conf/flyway.conf migrate
#    volumes:
#      - './app/flyway/conf:/flyway/conf'
#      - './app/flyway/sql:/flyway/sql'
#
#    networks:
#      - test
#
#networks:
#  test:
services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_DB=ZNO
            - POSTGRES_USER=Student
            - POSTGRES_PASSWORD=qwerty
        ports:
            - 5432:5432/tcp
        command: -c max_wal_size=5GB
    db_client:
        image: dpage/pgadmin4
        restart: always
        environment:
           - PGADMIN_DEFAULT_EMAIL=user@domain.com
           - PGADMIN_DEFAULT_PASSWORD=clientpass
        ports:
           - 5050:80
    flyway:
        image: flyway/flyway:7
        depends_on:
            - db
        volumes:
            - './app/flyway/conf:/flyway/conf'
            - './app/flyway/migrations:/flyway/sql'
        command: -configFiles=/flyway/conf/flyway.conf migrate
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
           - db
        volumes:
           - './app/data:/app/data'
           - './app/program_output:/app/program_output'
           - './app/flyway/migrations:/app/flyway/migrations'
    result_app:
        build:
            context: ./result_app
            dockerfile: Dockerfile
        depends_on:
            - db
